### ISSUE TITLE
Should ADMPRINCIPAL be FULLPRINCIPAL ?

### ISSUE THREAD

**Issue by jaltman** [scientificlinux/kcron#17]
On line 64 of kcroninit, should the principal name $USER/cron/$HOST@$REALM be assigned to FULLPRINCPAL instead of ADMPRINCIPAL?

https://github.com/scientificlinux/kcron/blob/41028c2a6037e8b4528532aa3ee7be6452f5dffe/src/shell/kcroninit#L64

**Comment by jcpunk** [comment]
@terlyga any thoughts?

**Comment by terlyga** [comment]
I don't think so. ADMPRINCIPAL is a principal that will be creating cron principal. 

If principal $USER@REALM  exist and local account $USER exists on the machine, then $USER is ADMPRINCIPAL. 

But sometimes cron principal is needed for local accounts, not associated with any individual principals in REALM. Say $USER account exists locally on the machine, but it does not exist in Kerberos realm. In that case, Kerberos admin could create $USER/cron/$HOST@$REALM, which can then be used to extract keytab for kcron. So $USER/cron/$HOST@$REALM is ADMPRINCIPAL.
