### ISSUE TITLE
Documentation request - what configuration is required on the KDC side?

### ISSUE THREAD

**Issue by jaltman** [scientificlinux/kcron#18]
It would be useful if documentation could be provided that describes what configuration is required on the KDC to permit users to create and destroy principals of the form 

   $USER/cron/$HOST@$REALM

without the user being granted the permission to create arbitrary principals.

**Comment by jcpunk** [comment]
@terlyga any thoughts?

**Comment by terlyga** [comment]
Good point.  I should add that. A line similar to the following should be added to kadm5.acl 

*@EXAMPLE.COM	                        acdim   *1/cron/*@EXAMPLE.COM

with whatever flags or policies you want to give to cron principals in your realm.

**Comment by jcpunk** [comment]
Sounds good, can you submit a pull request?  I'll get it merged.

**Comment by terlyga** [comment]
Umm,  no idea what "pull request" means. Should I read github help or something?

________________________________

**Comment by terlyga** [comment]
@jcpunk created a pull request
